/* eslint-disable */
// This file is generated by miqi.runtime.export_app_protocol_ts.
// Do not edit by hand; update Python request models and regenerate.

export const APP_PROTOCOL_GENERATED_AT = 'static' as const;

export type JsonValue =
  null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
export type EmptyObject = Record<string, never>;

export interface ChatAbortParams {
  thread_id?: null | string;
}

export interface CommandExecParams {
  command: string[];
  cwd?: null | string;
  deltaBase64?: null | string;
  disableOutputCap?: boolean;
  disableTimeout?: boolean;
  env?: Record<string, unknown> | null;
  outputBytesCap?: null | number;
  processId?: null | string;
  size?: null | unknown;
  streamStdin?: boolean;
  streamStdoutStderr?: boolean;
  timeoutMs?: null | number;
  tty?: boolean;
}

export interface CommandExecResizeParams {
  processId?: null | string;
}

export interface CommandExecTerminateParams {
  processId: string;
}

export interface CommandExecWriteParams {
  closeStdin?: boolean;
  deltaBase64?: null | string;
  processId: string;
}

export interface ConfigGetParams {}

export interface ConfigUpdateParams {
  config: Record<string, unknown>;
  expectModel?: null | string;
}

export interface ConfigBatchWriteParams {
  edits: unknown[];
  reloadUserConfig?: boolean;
}

export interface ConfigReadParams {}

export interface ExperimentalFeatureEnablementSetParams {
  enablement?: Record<string, unknown> | null;
  features?: Record<string, unknown>;
}

export interface ExperimentalFeatureListParams {
  cursor?: null | string;
  limit?: number;
  threadId?: null | string;
}

export interface FsCopyParams {
  destinationPath: string;
  recursive?: boolean;
  sourcePath: string;
}

export interface FsCreateDirectoryParams {
  path: string;
  recursive?: boolean;
}

export interface FsGetMetadataParams {
  path: string;
}

export interface FsReadDirectoryParams {
  path: string;
}

export interface FsReadFileParams {
  path: string;
}

export interface FsRemoveParams {
  force?: boolean;
  path: string;
  recursive?: boolean;
}

export interface FsUnwatchParams {
  watchId: string;
}

export interface FsWatchParams {
  path: string;
  watchId: string;
}

export interface FsWriteFileParams {
  dataBase64: string;
  path: string;
}

export interface FuzzyFileSearchParams {
  query: string;
  roots: string[];
}

export interface FuzzySessionStartParams {
  roots: string[];
  sessionId: string;
}

export interface FuzzySessionStopParams {
  sessionId: string;
}

export interface FuzzySessionUpdateParams {
  query: string;
  sessionId: string;
}

export interface HooksListParams {
  cwds?: string[];
}

export interface InitializeParams {
  capabilities?: null | unknown;
  clientId?: null | string;
  clientInfo: unknown;
}

export interface InitializedParams {}

export interface MarketplaceAddParams {
  marketplaceName?: null | string;
  name?: string;
  source?: string;
}

export interface MarketplaceRemoveParams {
  marketplaceName?: null | string;
  name?: string;
}

export interface MarketplaceUpgradeParams {
  marketplaceName?: null | string;
}

export interface ModelListParams {
  includeHidden?: boolean;
}

export interface ModelProviderCapabilitiesReadParams {
  provider?: null | string;
  providerName?: null | string;
}

export interface PermissionProfileListParams {
  cursor?: null | string;
  limit?: number;
}

export interface PluginInstallParams {
  name?: null | string;
  pluginId?: null | string;
  pluginName?: string;
  source?: string;
  url?: null | string;
}

export interface PluginInstalledParams {}

export interface PluginListParams {}

export interface PluginReadParams {
  marketplaceName?: null | string;
  name?: null | string;
  pluginName?: string;
}

export interface PluginSkillReadParams {
  marketplaceName?: null | string;
  pluginName?: string;
  skillName?: string;
}

export interface PluginUninstallParams {
  name?: null | string;
  pluginId?: string;
  pluginName?: null | string;
}

export interface ProcessKillParams {
  processHandle: string;
}

export interface ProcessResizePtyParams {
  processHandle?: null | string;
}

export interface ProcessSpawnParams {
  command: string[];
  cwd: string;
  disableOutputCap?: boolean;
  disableTimeout?: boolean;
  env?: Record<string, unknown> | null;
  outputBytesCap?: null | number;
  processHandle: string;
  streamStdoutStderr?: boolean;
  timeoutMs?: null | number;
  tty?: boolean;
}

export interface ProcessWriteStdinParams {
  closeStdin?: boolean;
  deltaBase64?: null | string;
  processHandle: string;
}

export interface PythonCheckParams {}

export interface SessionsArchiveParams {
  sessionKey?: string;
  workspace?: null | string;
}

export interface SessionsClaimLegacyParams {
  sessionKey?: string;
  workspace?: null | string;
}

export interface SessionsClearTrackedFilesParams {
  sessionKey?: string;
  workspace?: null | string;
}

export interface SessionsDeleteParams {
  sessionKey?: string;
  workspace?: null | string;
}

export interface SessionsGetParams {
  sessionKey?: string;
  workspace?: null | string;
}

export interface SessionsGetTrackedFilesParams {
  sessionKey?: string;
  workspace?: null | string;
}

export interface SessionsListParams {}

export interface SessionsListArchivedParams {}

export interface SessionsRenameParams {
  sessionKey?: string;
  title?: null | string;
  workspace?: null | string;
}

export interface SessionsUnarchiveParams {
  sessionKey?: string;
  workspace?: null | string;
}

export interface SkillsExtraRootsSetParams {
  roots: string[];
}

export interface SkillsListParams {
  cwds?: string[];
}

export interface StatusParams {}

export interface ThreadArchiveCompatParams {
  thread_id?: string;
}

export interface ThreadCreateCompatParams {
  thread_id?: null | string;
  title?: null | string;
}

export interface ThreadDeleteCompatParams {
  thread_id?: string;
}

export interface ThreadListCompatParams {}

export interface ThreadRenameCompatParams {
  thread_id?: string;
  title?: string;
}

export interface ThreadCompactStartParams {
  threadId: string;
}

export interface ThreadExportParams {
  sessionId?: null | string;
  threadId?: string;
}

export interface ThreadForkParams {
  excludeTurns?: boolean;
  itemsView?: null | string;
  sessionId?: null | string;
  threadId?: string;
  title?: null | string;
}

export interface ThreadImportParams {
  document?: Record<string, unknown> | null;
  includeTurns?: boolean;
  overwrite?: boolean;
  sessionId?: null | string;
  sessionKey?: null | string;
  threadId?: null | string;
}

export interface ThreadInjectItemsParams {
  items: Record<string, unknown>[];
  threadId: string;
}

export interface ThreadListParams {
  archived?: boolean;
  cursor?: null | string;
  limit?: number;
  searchTerm?: null | string;
  sessionId?: null | string;
  sortDirection?: null | string;
}

export interface ThreadLoadedListParams {}

export interface ThreadNameSetParams {
  name?: string;
  threadId?: string;
}

export interface ThreadReadParams {
  includeTurns?: boolean;
  itemsView?: null | string;
  sessionId?: null | string;
  threadId?: string;
}

export interface ThreadResumeParams {
  excludeTurns?: boolean;
  itemsView?: null | string;
  sessionId?: null | string;
  sessionKey?: null | string;
  threadId?: string;
}

export interface ThreadRollbackParams {
  dropLastTurns?: number;
  itemsView?: null | string;
  numTurns?: null | number;
  sessionId?: null | string;
  threadId?: string;
}

export interface ThreadStartParams {
  ephemeral?: boolean;
  name?: null | string;
  sessionId?: null | string;
  sessionKey?: null | string;
  threadId?: null | string;
  title?: null | string;
}

export interface ThreadTurnsItemsListParams {
  threadId?: null | string;
}

export interface ThreadTurnsListParams {
  cursor?: null | string;
  itemsView?: null | string;
  limit?: number;
  sessionId?: null | string;
  sortDirection?: null | string;
  threadId?: string;
}

export interface TurnInterruptParams {
  threadId: string;
  turnId: string;
}

export interface TurnStartParams {
  clientUserMessageId?: null | string;
  effort?: null | string;
  environments?: null | unknown;
  input: Record<string, unknown>[];
  model?: null | string;
  outputSchema?: null | unknown;
  personality?: null | string;
  summary?: null | string;
  threadId: string;
}

export interface TurnSteerParams {
  clientUserMessageId?: null | string;
  expectedTurnId: string;
  input: Record<string, unknown>[];
  threadId: string;
}

export interface ChatAbortResult {
  aborted: boolean;
}

export interface CommandExecResult {
  durationMs: number;
  exitCode: number;
  stderr: string;
  stderrCapReached: boolean;
  stdout: string;
  stdoutCapReached: boolean;
  terminationReason: null | string;
}

export interface CommandExecResizeResult {}

export interface CommandExecTerminateResult {}

export interface CommandExecWriteResult {}

export interface ConfigGetResult {}

export interface ConfigUpdateResult {
  propagated_sessions: number;
  saved: boolean;
}

export interface ConfigBatchWriteResult {
  applied: number;
  propagatedSessions: number;
  saved: boolean;
}

export interface ConfigReadResult {}

export interface ExperimentalFeatureEnablementSetResult {
  ignored: string[];
  saved: boolean;
}

export interface ExperimentalFeatureListResult {
  data: Record<string, unknown>[];
  nextCursor?: null | string;
}

export interface FsCopyResult {}

export interface FsCreateDirectoryResult {}

export interface FsGetMetadataResult {
  createdAtMs: number;
  isDirectory: boolean;
  isFile: boolean;
  isSymlink: boolean;
  modifiedAtMs: number;
}

export interface FsReadDirectoryResult {
  entries: unknown[];
}

export interface FsReadFileResult {
  dataBase64: string;
}

export interface FsRemoveResult {}

export interface FsUnwatchResult {}

export interface FsWatchResult {
  path: string;
}

export interface FsWriteFileResult {}

export interface FuzzyFileSearchResult {
  files: unknown[];
}

export interface FuzzySessionStartResult {}

export interface FuzzySessionStopResult {}

export interface FuzzySessionUpdateResult {}

export interface HooksListResult {
  hooks: Record<string, unknown>[];
}

export interface InitializeResult {
  capabilities: unknown;
  clientId: string;
  codexHome: string;
  miqiHome: string;
  platformFamily: string;
  platformOs: string;
  serverInfo: unknown;
  userAgent: string;
}

export interface InitializedResult {}

export interface MarketplaceAddResult {
  alreadyPresent: boolean;
  marketplace: Record<string, unknown>;
}

export interface MarketplaceRemoveResult {
  marketplaceName: string;
  removed: boolean;
}

export interface MarketplaceUpgradeResult {
  errors?: Record<string, unknown>[];
  selectedMarketplaces: string[];
}

export interface ModelListResult {
  models: Record<string, unknown>[];
}

export interface ModelProviderCapabilitiesReadResult {
  capabilities: Record<string, unknown>;
}

export interface PermissionProfileListResult {
  data: Record<string, unknown>[];
  nextCursor?: null | string;
}

export interface PluginInstallResult {
  plugin: Record<string, unknown>;
}

export interface PluginInstalledResult {
  plugins: Record<string, unknown>[];
}

export interface PluginListResult {
  featuredPluginIds?: string[];
  marketplaceLoadErrors?: Record<string, unknown>[];
  marketplaces: Record<string, unknown>[];
  plugins: Record<string, unknown>[];
}

export interface PluginReadResult {
  plugin: Record<string, unknown>;
}

export interface PluginSkillReadResult {
  content: string;
}

export interface PluginUninstallResult {
  pluginId: string;
  removed: boolean;
}

export interface ProcessKillResult {}

export interface ProcessResizePtyResult {}

export interface ProcessSpawnResult {}

export interface ProcessWriteStdinResult {}

export interface PythonCheckResult {
  config_exists: boolean;
  issues: string[];
  ok: boolean;
  python_version: string;
}

export interface SessionsArchiveResult {
  archived: boolean;
}

export interface SessionsClaimLegacyResult {
  claimed: boolean;
  was_already_claimed: boolean;
}

export interface SessionsClearTrackedFilesResult {
  cleared: boolean;
}

export interface SessionsDeleteResult {
  deleted: boolean;
}

export interface SessionsGetResult {
  agent_count?: null | number;
  created_at?: null | string;
  key?: null | string;
  messages?: Record<string, unknown>[] | null;
  metadata?: Record<string, unknown> | null;
  ownership?: null | string;
  session_id?: null | string;
  status?: null | string;
  updated_at?: null | string;
}

export interface SessionsGetTrackedFilesResult {
  tracked_files: Record<string, unknown>[];
}

export interface SessionsListResult {
  sessions: Record<string, unknown>[];
}

export interface SessionsListArchivedResult {
  sessions: Record<string, unknown>[];
}

export interface SessionsRenameResult {
  key?: null | string;
  renamed?: boolean;
  title?: null | string;
}

export interface SessionsUnarchiveResult {
  unarchived: boolean;
}

export interface SkillsExtraRootsSetResult {}

export interface SkillsListResult {
  skills: Record<string, unknown>[];
}

export interface StatusResult {
  configured: boolean;
  python_version: string;
  status: string;
}

export interface ThreadArchiveCompatResult {
  status: string;
  thread_id: string;
}

export interface ThreadCreateCompatResult {
  parent_thread_id?: null | string;
  thread_id: string;
  title: string;
}

export interface ThreadDeleteCompatResult {
  deleted: boolean;
}

export interface ThreadListCompatResult {
  threads: Record<string, unknown>[];
}

export interface ThreadRenameCompatResult {
  thread_id: string;
  title: string;
}

export interface ThreadExportResult {
  document: Record<string, unknown>;
}

export interface ThreadForkResult {
  thread: Record<string, unknown>;
}

export interface ThreadImportResult {
  thread: Record<string, unknown>;
}

export interface ThreadListResult {
  items: Record<string, unknown>[];
  nextCursor?: null | string;
}

export interface ThreadLoadedListResult {
  threadIds: string[];
}

export interface ThreadNameSetResult {
  thread: Record<string, unknown>;
}

export interface ThreadReadResult {
  thread: Record<string, unknown>;
}

export interface ThreadResumeResult {
  thread: Record<string, unknown>;
}

export interface ThreadRollbackResult {
  thread: Record<string, unknown>;
}

export interface ThreadStartResult {
  thread: Record<string, unknown>;
}

export interface ThreadTurnsItemsListResult {}

export interface ThreadTurnsListResult {
  items: Record<string, unknown>[];
  nextCursor?: null | string;
}

export interface CommandExecOutputDeltaEventPayload {
  capReached: boolean;
  deltaBase64: string;
  processId: string;
  stream: string;
}

export interface FsChangedEventPayload {
  changedPaths: string[];
  watchId: string;
}

export interface FuzzySessionCompletedEventPayload {
  sessionId: string;
}

export interface FuzzySessionUpdatedEventPayload {
  files: unknown[];
  query: string;
  sessionId: string;
}

export interface ProcessExitedEventPayload {
  durationMs: number;
  exitCode: number;
  processHandle: string;
  stderr: string;
  stderrCapReached: boolean;
  stdout: string;
  stdoutCapReached: boolean;
  terminationReason: null | string;
}

export interface ProcessOutputDeltaEventPayload {
  capReached: boolean;
  deltaBase64: string;
  processHandle: string;
  stream: string;
}

export const APP_METHODS = [
  'chat.abort',
  'command/exec',
  'command/exec/resize',
  'command/exec/terminate',
  'command/exec/write',
  'config.get',
  'config.update',
  'config/batchWrite',
  'config/read',
  'experimentalFeature/enablement/set',
  'experimentalFeature/list',
  'fs/copy',
  'fs/createDirectory',
  'fs/getMetadata',
  'fs/readDirectory',
  'fs/readFile',
  'fs/remove',
  'fs/unwatch',
  'fs/watch',
  'fs/writeFile',
  'fuzzyFileSearch',
  'fuzzyFileSearch/sessionStart',
  'fuzzyFileSearch/sessionStop',
  'fuzzyFileSearch/sessionUpdate',
  'hooks/list',
  'initialize',
  'initialized',
  'marketplace/add',
  'marketplace/remove',
  'marketplace/upgrade',
  'model/list',
  'modelProvider/capabilities/read',
  'permissionProfile/list',
  'plugin/install',
  'plugin/installed',
  'plugin/list',
  'plugin/read',
  'plugin/skill/read',
  'plugin/uninstall',
  'process/kill',
  'process/resizePty',
  'process/spawn',
  'process/writeStdin',
  'python.check',
  'sessions.archive',
  'sessions.claim_legacy',
  'sessions.clear_tracked_files',
  'sessions.delete',
  'sessions.get',
  'sessions.get_tracked_files',
  'sessions.list',
  'sessions.list_archived',
  'sessions.rename',
  'sessions.unarchive',
  'skills/extraRoots/set',
  'skills/list',
  'status',
  'thread.archive',
  'thread.create',
  'thread.delete',
  'thread.list',
  'thread.rename',
  'thread/compact/start',
  'thread/export',
  'thread/fork',
  'thread/import',
  'thread/inject_items',
  'thread/list',
  'thread/loaded/list',
  'thread/name/set',
  'thread/read',
  'thread/resume',
  'thread/rollback',
  'thread/start',
  'thread/turns/items/list',
  'thread/turns/list',
  'turn/interrupt',
  'turn/start',
  'turn/steer',
] as const;
export type AppMethod = (typeof APP_METHODS)[number];

export interface AppMethodParams {
  'chat.abort': ChatAbortParams;
  'command/exec': CommandExecParams;
  'command/exec/resize': CommandExecResizeParams;
  'command/exec/terminate': CommandExecTerminateParams;
  'command/exec/write': CommandExecWriteParams;
  'config.get': ConfigGetParams;
  'config.update': ConfigUpdateParams;
  'config/batchWrite': ConfigBatchWriteParams;
  'config/read': ConfigReadParams;
  'experimentalFeature/enablement/set': ExperimentalFeatureEnablementSetParams;
  'experimentalFeature/list': ExperimentalFeatureListParams;
  'fs/copy': FsCopyParams;
  'fs/createDirectory': FsCreateDirectoryParams;
  'fs/getMetadata': FsGetMetadataParams;
  'fs/readDirectory': FsReadDirectoryParams;
  'fs/readFile': FsReadFileParams;
  'fs/remove': FsRemoveParams;
  'fs/unwatch': FsUnwatchParams;
  'fs/watch': FsWatchParams;
  'fs/writeFile': FsWriteFileParams;
  'fuzzyFileSearch': FuzzyFileSearchParams;
  'fuzzyFileSearch/sessionStart': FuzzySessionStartParams;
  'fuzzyFileSearch/sessionStop': FuzzySessionStopParams;
  'fuzzyFileSearch/sessionUpdate': FuzzySessionUpdateParams;
  'hooks/list': HooksListParams;
  'initialize': InitializeParams;
  'initialized': InitializedParams;
  'marketplace/add': MarketplaceAddParams;
  'marketplace/remove': MarketplaceRemoveParams;
  'marketplace/upgrade': MarketplaceUpgradeParams;
  'model/list': ModelListParams;
  'modelProvider/capabilities/read': ModelProviderCapabilitiesReadParams;
  'permissionProfile/list': PermissionProfileListParams;
  'plugin/install': PluginInstallParams;
  'plugin/installed': PluginInstalledParams;
  'plugin/list': PluginListParams;
  'plugin/read': PluginReadParams;
  'plugin/skill/read': PluginSkillReadParams;
  'plugin/uninstall': PluginUninstallParams;
  'process/kill': ProcessKillParams;
  'process/resizePty': ProcessResizePtyParams;
  'process/spawn': ProcessSpawnParams;
  'process/writeStdin': ProcessWriteStdinParams;
  'python.check': PythonCheckParams;
  'sessions.archive': SessionsArchiveParams;
  'sessions.claim_legacy': SessionsClaimLegacyParams;
  'sessions.clear_tracked_files': SessionsClearTrackedFilesParams;
  'sessions.delete': SessionsDeleteParams;
  'sessions.get': SessionsGetParams;
  'sessions.get_tracked_files': SessionsGetTrackedFilesParams;
  'sessions.list': SessionsListParams;
  'sessions.list_archived': SessionsListArchivedParams;
  'sessions.rename': SessionsRenameParams;
  'sessions.unarchive': SessionsUnarchiveParams;
  'skills/extraRoots/set': SkillsExtraRootsSetParams;
  'skills/list': SkillsListParams;
  'status': StatusParams;
  'thread.archive': ThreadArchiveCompatParams;
  'thread.create': ThreadCreateCompatParams;
  'thread.delete': ThreadDeleteCompatParams;
  'thread.list': ThreadListCompatParams;
  'thread.rename': ThreadRenameCompatParams;
  'thread/compact/start': ThreadCompactStartParams;
  'thread/export': ThreadExportParams;
  'thread/fork': ThreadForkParams;
  'thread/import': ThreadImportParams;
  'thread/inject_items': ThreadInjectItemsParams;
  'thread/list': ThreadListParams;
  'thread/loaded/list': ThreadLoadedListParams;
  'thread/name/set': ThreadNameSetParams;
  'thread/read': ThreadReadParams;
  'thread/resume': ThreadResumeParams;
  'thread/rollback': ThreadRollbackParams;
  'thread/start': ThreadStartParams;
  'thread/turns/items/list': ThreadTurnsItemsListParams;
  'thread/turns/list': ThreadTurnsListParams;
  'turn/interrupt': TurnInterruptParams;
  'turn/start': TurnStartParams;
  'turn/steer': TurnSteerParams;
}

export interface AppMethodResult {
  'chat.abort': ChatAbortResult;
  'command/exec': CommandExecResult;
  'command/exec/resize': CommandExecResizeResult;
  'command/exec/terminate': CommandExecTerminateResult;
  'command/exec/write': CommandExecWriteResult;
  'config.get': ConfigGetResult;
  'config.update': ConfigUpdateResult;
  'config/batchWrite': ConfigBatchWriteResult;
  'config/read': ConfigReadResult;
  'experimentalFeature/enablement/set': ExperimentalFeatureEnablementSetResult;
  'experimentalFeature/list': ExperimentalFeatureListResult;
  'fs/copy': FsCopyResult;
  'fs/createDirectory': FsCreateDirectoryResult;
  'fs/getMetadata': FsGetMetadataResult;
  'fs/readDirectory': FsReadDirectoryResult;
  'fs/readFile': FsReadFileResult;
  'fs/remove': FsRemoveResult;
  'fs/unwatch': FsUnwatchResult;
  'fs/watch': FsWatchResult;
  'fs/writeFile': FsWriteFileResult;
  'fuzzyFileSearch': FuzzyFileSearchResult;
  'fuzzyFileSearch/sessionStart': FuzzySessionStartResult;
  'fuzzyFileSearch/sessionStop': FuzzySessionStopResult;
  'fuzzyFileSearch/sessionUpdate': FuzzySessionUpdateResult;
  'hooks/list': HooksListResult;
  'initialize': InitializeResult;
  'initialized': InitializedResult;
  'marketplace/add': MarketplaceAddResult;
  'marketplace/remove': MarketplaceRemoveResult;
  'marketplace/upgrade': MarketplaceUpgradeResult;
  'model/list': ModelListResult;
  'modelProvider/capabilities/read': ModelProviderCapabilitiesReadResult;
  'permissionProfile/list': PermissionProfileListResult;
  'plugin/install': PluginInstallResult;
  'plugin/installed': PluginInstalledResult;
  'plugin/list': PluginListResult;
  'plugin/read': PluginReadResult;
  'plugin/skill/read': PluginSkillReadResult;
  'plugin/uninstall': PluginUninstallResult;
  'process/kill': ProcessKillResult;
  'process/resizePty': ProcessResizePtyResult;
  'process/spawn': ProcessSpawnResult;
  'process/writeStdin': ProcessWriteStdinResult;
  'python.check': PythonCheckResult;
  'sessions.archive': SessionsArchiveResult;
  'sessions.claim_legacy': SessionsClaimLegacyResult;
  'sessions.clear_tracked_files': SessionsClearTrackedFilesResult;
  'sessions.delete': SessionsDeleteResult;
  'sessions.get': SessionsGetResult;
  'sessions.get_tracked_files': SessionsGetTrackedFilesResult;
  'sessions.list': SessionsListResult;
  'sessions.list_archived': SessionsListArchivedResult;
  'sessions.rename': SessionsRenameResult;
  'sessions.unarchive': SessionsUnarchiveResult;
  'skills/extraRoots/set': SkillsExtraRootsSetResult;
  'skills/list': SkillsListResult;
  'status': StatusResult;
  'thread.archive': ThreadArchiveCompatResult;
  'thread.create': ThreadCreateCompatResult;
  'thread.delete': ThreadDeleteCompatResult;
  'thread.list': ThreadListCompatResult;
  'thread.rename': ThreadRenameCompatResult;
  'thread/compact/start': Record<string, unknown>;
  'thread/export': ThreadExportResult;
  'thread/fork': ThreadForkResult;
  'thread/import': ThreadImportResult;
  'thread/inject_items': Record<string, unknown>;
  'thread/list': ThreadListResult;
  'thread/loaded/list': ThreadLoadedListResult;
  'thread/name/set': ThreadNameSetResult;
  'thread/read': ThreadReadResult;
  'thread/resume': ThreadResumeResult;
  'thread/rollback': ThreadRollbackResult;
  'thread/start': ThreadStartResult;
  'thread/turns/items/list': ThreadTurnsItemsListResult;
  'thread/turns/list': ThreadTurnsListResult;
  'turn/interrupt': Record<string, unknown>;
  'turn/start': Record<string, unknown>;
  'turn/steer': Record<string, unknown>;
}

export interface AppMethodEvents {
  'chat.abort': never;
  'command/exec': 'command/exec/outputDelta';
  'command/exec/resize': never;
  'command/exec/terminate': never;
  'command/exec/write': never;
  'config.get': never;
  'config.update': never;
  'config/batchWrite': never;
  'config/read': never;
  'experimentalFeature/enablement/set': never;
  'experimentalFeature/list': never;
  'fs/copy': never;
  'fs/createDirectory': never;
  'fs/getMetadata': never;
  'fs/readDirectory': never;
  'fs/readFile': never;
  'fs/remove': never;
  'fs/unwatch': never;
  'fs/watch': 'fs/changed';
  'fs/writeFile': never;
  'fuzzyFileSearch': never;
  'fuzzyFileSearch/sessionStart': never;
  'fuzzyFileSearch/sessionStop': never;
  'fuzzyFileSearch/sessionUpdate': 'fuzzyFileSearch/sessionCompleted' | 'fuzzyFileSearch/sessionUpdated';
  'hooks/list': never;
  'initialize': never;
  'initialized': never;
  'marketplace/add': never;
  'marketplace/remove': never;
  'marketplace/upgrade': never;
  'model/list': never;
  'modelProvider/capabilities/read': never;
  'permissionProfile/list': never;
  'plugin/install': never;
  'plugin/installed': never;
  'plugin/list': never;
  'plugin/read': never;
  'plugin/skill/read': never;
  'plugin/uninstall': never;
  'process/kill': never;
  'process/resizePty': never;
  'process/spawn': 'process/exited' | 'process/outputDelta';
  'process/writeStdin': never;
  'python.check': never;
  'sessions.archive': never;
  'sessions.claim_legacy': never;
  'sessions.clear_tracked_files': never;
  'sessions.delete': never;
  'sessions.get': never;
  'sessions.get_tracked_files': never;
  'sessions.list': never;
  'sessions.list_archived': never;
  'sessions.rename': never;
  'sessions.unarchive': never;
  'skills/extraRoots/set': 'skills/changed';
  'skills/list': never;
  'status': never;
  'thread.archive': never;
  'thread.create': never;
  'thread.delete': never;
  'thread.list': never;
  'thread.rename': never;
  'thread/compact/start': 'item/completed' | 'item/started' | 'turn/completed' | 'turn/started';
  'thread/export': never;
  'thread/fork': 'thread/started';
  'thread/import': never;
  'thread/inject_items': never;
  'thread/list': never;
  'thread/loaded/list': never;
  'thread/name/set': 'thread/name/updated';
  'thread/read': never;
  'thread/resume': 'thread/started';
  'thread/rollback': 'thread/rollback';
  'thread/start': 'thread/started';
  'thread/turns/items/list': never;
  'thread/turns/list': never;
  'turn/interrupt': never;
  'turn/start': 'item/completed' | 'item/started' | 'turn/completed' | 'turn/started';
  'turn/steer': never;
}

export interface AppEventPayloadMap {
  'command/exec/outputDelta': CommandExecOutputDeltaEventPayload;
  'fs/changed': FsChangedEventPayload;
  'fuzzyFileSearch/sessionCompleted': FuzzySessionCompletedEventPayload;
  'fuzzyFileSearch/sessionUpdated': FuzzySessionUpdatedEventPayload;
  'process/exited': ProcessExitedEventPayload;
  'process/outputDelta': ProcessOutputDeltaEventPayload;
}
export type AppEventName = keyof AppEventPayloadMap;

export type AppEventPayload<E extends AppEventName> = AppEventPayloadMap[E];

export type AppRequest<M extends AppMethod = AppMethod> = {
  id: string;
  method: M;
  params: AppMethodParams[M];
};

export type AppResult<M extends AppMethod> = AppMethodResult[M];
export type AppParams<M extends AppMethod> = AppMethodParams[M];
export type AppEvent<M extends AppMethod> = AppMethodEvents[M];
